### ISSUE TITLE
V11

### ISSUE THREAD

**Issue by Kerdian** [Dellatosa/Agone#12]
Bonjour, 
Une petite question, comptez vous faire la MAJ vers la V11 de Foundry pour Agone?
Dans tout les cas, merci pour le boulot fait.

**Comment by Dellatosa** [comment]
Bonjour,

Oui j'adapterai le système en V11, mais je ne sais pas dire sous combien de temps il sera disponible. Je n'ai pas encore regardé dans le détail les breaking changes entre la v10 et la v11, et leur impacts sur le système.

Je me pencherai sur le sujet à partir du mois d'aout prochain (mon travail ne me laisse pas trop de dispo en ce moment).

Merci pour votre soutien :)

**Comment by Kerdian** [comment]
Merci pour le retour et le boulot.
