### ISSUE TITLE
Autre obédience

### ISSUE THREAD

**Issue by Gabryel666** [Dellatosa/Agone#8]
v.0.1.3
Lors du lancement d'un sort d'une autre obédience, le malus de "autre obédience" est bien pris en compte dans le jet, mais le jet reste interdit si le score de compétence de l'autre obédience est de 0.

**Point de règle ?**
Est ce que les règles interdisent de lancer d'autres sorts d'obédiences différentes si compétence à 0 ? Je trouve ça étrange car un malus est déjà appliqué.

**Point de dev ?**
Est ce que la règle générale de fermer les compétences occultes en utilisation à 0 ne vient pas perturber le lancer de sort.

**Comment by Dellatosa** [comment]
Je n'arrive pas à reproduire le problème. J'ai fait l'essai avec un personnage préexistant et un nouveau personnage, aussi bien en sort connu qu'en magie intuitive : 

![2021-07-26_17h40_02](https://user-images.githubusercontent.com/68203012/127021129-c1870595-a11d-499b-99ab-1fd4c1dedb99.png)

![2021-07-26_17h38_48](https://user-images.githubusercontent.com/68203012/127021062-d1c7c3b6-659d-46ab-8fe7-5d0c5bf695ff.png)

**Comment by Gabryel666** [comment]
Le problème survient quand on change l'obédience dans l'onglet magie.
![image](https://user-images.githubusercontent.com/65908230/127022589-a7db2861-d6cb-45e0-805a-25c49d8cc098.png)
Ce qui pour le coup est tout à fait normal.
J'avais changé l'obédience ici au départ pour tester.
Tout fonctionne donc normalement !
