### ISSUE TITLE
Erreur Tooltip

### ISSUE THREAD

**Issue by Gabryel666** [Dellatosa/Agone#9]
v 0.1.3
Le tooltip sur le dessin du sort dans la fiche actor dit  "_Jet de dés"_ alors que l'action de clic dessus fait apparaitre le sort dans le chat. Il faudrait le remplacer par _"Voir le sort"_

**Comment by Gabryel666** [comment]
Erreur identique sur l'image du danseur.

**Comment by Dellatosa** [comment]
Corrigé
